project: diting.tiny.trace.hdf5-slide_window
method: bayes
metric:
  name: e_angle_vector
  goal: minimize
parameters:
  embedding_dropout:
    values: [ 0, 0.1, 0.3, 0.5]
  retention_dropout:
    values: [ 0, 0.1, 0.3, 0.5]
  downstream_dropout:
    values: [ 0, 0.1, 0.3, 0.5]
command:
  - accelerate-launch 
  - --config_file 
  - config/accelerate/bf16_cards8_ds1.yaml 
  - train_single_station_via_llm_way.py 
  - --task 
  - train 
  - --epochs 
  - 50 
  - --downstream_task 
  - abs_angle_vector
  - --max_length 
  - 3000 
  - --num_workers 
  - 8 
  - --data_parallel_dispatch 
  - --resource_source 
  - diting.tiny.trace.hdf5 
  - --Resource 
  - DiTing 
  - --model
  - GoldfishW10M
  - --batch_size
  - 32
  - --warmup_epochs
  - 3
  - --use_wandb
  - --bandfilter_rate
  - 0.5 
  - --save_every_epoch
  - 10
  - --clean_checkpoints_at_end
  - --train_sampling_strategy.strategy_name
  - early_warning_before_p
  - --train_sampling_strategy.early_warning
  - 500
  - --valid_sampling_strategy.early_warning 
  - 500
  - --lr
  - 0.0001
  - ${args}
