program: train_single_station_via_llm_way.py
project: magtime.stead.trace
method: bayes
metric:
  name: validation/loss
  goal: minimize
parameters:
  lr:
    min: 0.0001
    max: 0.001
  seed:
    values: [19940928, 19950929, 20130901, 20230901]
command:
  - accelerate-launch
  - --main_process_port
  - 12345
  - ${program}
  - --batch_size 
  - 8
  - --use_wandb
  - --distance_unit 
  - 1 
  - --model_type 
  - longformer_sequence 
  - --warning_window 
  - 0 
  - --downstream_task 
  - abs_locdeep 
  - --max_length 
  - 6000 
  - --vocab_size 
  - 4
  - --find_unused_parameters
  - ${args}
